property-level: 'auth prod level'
spring:
  datasource:
    url: jdbc:mysql://bhoomitech-dev.cyojzfaxldo6.us-east-1.rds.amazonaws.com:3306/boomitech_auth?createDatabaseIfNotExist=true
    username: bhoomitech_rw
    password: Bh00miTecH
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  oauth2:
    resource:
      token-info-uri: http://ec2-54-175-165-177.compute-1.amazonaws.com:12002/oauth/check_token
    client:
      client-id: web
      client-secret: pin
      access-token-uri: http://ec2-54-175-165-177.compute-1.amazonaws.com:12002/oauth/token
      user-authorization-uri: http://ec2-54-175-165-177.compute-1.amazonaws.com:12002/oauth/authorize
logging:
  level:
    org:
      springframework:
        web: DEBUG
        FilterChainProxy: DEBUG
app:
  custom-configs:
    default-login-redirect: http://ec2-54-175-165-177.compute-1.amazonaws.com
    email:
      name: BHOOMITECH GNS SYSTEM
      address: noreply@bhoomitech.com
      password: bUH!4Laur*DhFxVrEl
      smtp-host: mail.bhoomitech.com
      smtp-port: 587
      reset-password:
        subject: Reset you password
        body: Hello {user_name}, please click the following link to reset your account password.
        url: http://ec2-54-175-165-177.compute-1.amazonaws.com:12002/reset-password?token={token}
      activate:
        subject: Activate your account
        body: Hello {user_name}, please click the following link to activate your account.
        url: http://ec2-54-175-165-177.compute-1.amazonaws.com:12002/activate?token={token}



